### ISSUE TITLE
Expose Stream Watermarks

### ISSUE THREAD

**Issue by benjamingr** [whatwg/fetch#689] opened 2018-04-02 15:54 UTC
ReadableStreams support buffering with watermarks but that capability is not exposed to `fetch`.

I have a use case where I want to download videos with `fetch` and control how much buffering happens in the background.

Eventually, I want to be able to implement something like the Chrome video tag with `fetch`. It would be great to have the capability exposed.

**Comment by domenic** [comment] 2018-04-02 16:04
/cc @ricea @yutakahirano. At least in our implementation this would be pretty easy to add, right?

To be clear, this wouldn't be a perfect upper bound probably (since there are other layers of the stack that have their own buffering), but it would give some level of control.

**Comment by yutakahirano** [comment] 2018-04-03 02:26
Chrome fetch() implementation doesn't buffer things __in ReadableStream__ (i.e., it's always created with CountQueuingStrategy(0)). As @domenic said, there are other layers doing buffering, so I'm not sure if exposing it makes much sense.

**Comment by domenic** [comment] 2018-04-03 02:33
Hmm, right. So I guess this would allow you to _add_ buffering, not control it. But, you can also do that [relatively easily](https://streams.spec.whatwg.org/#example-transform-identity) with an identity transform stream. Would that suffice for your purposes, @benjamingr? Or are you looking for more control?

**Comment by benjamingr** [comment] 2018-04-03 07:12
@domenic when I do a `fetch('file')` to a large file and get a reader - even if I don't actually read anything from it it will download the whole file. So I guess I should file a bug for that?

As for Chrome fetch - maybe the behavior should be specced so other browsers all behave consistently?

**Comment by ricea** [comment] 2018-04-03 08:08
@benjamingr The lack of backpressure is a deficiency in Chrome's implementation. See https://bugs.chromium.org/p/chromium/issues/detail?id=535793.

In general, if you need to _add_ buffering, piping through a `new TransformStream(undefined, new ByteLengthQueuingStrategy({highWaterMark: 16 * 1024 * 1024}))` is the way to go.

_Removing_ buffering would be somewhere between "hard to implement" and "infeasible". There are multiple layers of buffering in place, all of which serve a purpose and some of which are outside of the control of the browser implementer. It might be possible to have a "hint" to implementations that a particular fetch wants reduced buffering, but I expect it would end up with all implementations ignoring the hint completely.

**Comment by jakearchibald** [comment] 2018-04-03 08:16
@benjamingr demo: https://fetch-flow-control-demo.glitch.me/

This seems to work for no-store today, or are you wanting something different?

**Comment by benjamingr** [comment] 2018-04-03 12:41
Just exposing watermarks would be a great start for what I need, although to be fair it looks like no browsers handle backpressure:

```
(async () => {
   const r = await fetch('https://storage.googleapis.com/long-mp4-file.mp4', {
     cache: 'no-store'
   });
   const reader = r.body.getReader();
   var i = 10;
   while(i --> 0) { 
     await new Promise(r => setTimeout(r, 2000));
     console.log(await reader.read());
   }
   reader.cancel();
})(); 
```

Every browser I tested (FF, Safari and Chrome) downloaded the whole 75mb video. Is this just a bug in the implementation or am I doing something wrong?

**Comment by jakearchibald** [comment] 2018-04-03 12:55
That feels like an implementation bug to me. @ricea is this part of https://bugs.chromium.org/p/chromium/issues/detail?id=535793 or a new bug?

I've updated https://fetch-flow-control-demo.glitch.me/ with a test.

**Comment by jakearchibald** [comment] 2018-04-03 12:57
@benjamingr 

> Just exposing watermarks would be a great start for what I need

Exposing them in what way? If the no-store bug you mentioned was fixed (as in, it would behave like the no-store response on https://fetch-flow-control-demo.glitch.me/), is there anything else you need?

**Comment by ricea** [comment] 2018-04-03 13:14
@jakearchibald Yes, part of https://bugs.chromium.org/p/chromium/issues/detail?id=535793. Blink only looks at the Cache-Control header on the response, nothing else. We should probably also make it respect cache: "no-store" on the request object.

**Comment by benjamingr** [comment] 2018-04-03 13:19
@ricea that would be awesome, though it's worth mentioning that Chrome's current behavior is also the case for all other implementors.

**Comment by ricea** [comment] 2018-04-03 13:24
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=828386 about making { cache: "no-store" } apply backpressure.

**Comment by benjamingr** [comment] 2018-04-03 14:09
@ricea any estimate of how hard it is (and whether or not someone will get to it in the forseeable future?). Also, should we file bugs against Firefox, Safari and Edge?

**Comment by ricea** [comment] 2018-04-03 14:27
@benjamingr You can hack something together using a mixture of Range requests and fetch abort, but it won't be pretty.

**Comment by guest271314** [comment] 2018-04-07 20:58
@benjamingr If the requirement is only displaying the video and not recording the video as the stream is ongoing you can use `MediaSource` attached to a `<video>` element and the elements' `waiting` element to determine when to fetch the next chunks, see https://github.com/guest271314/MediaFragmentRecorder.

**Comment by guest271314** [comment] 2018-04-07 21:02
@benjamingr If the requirement is only displaying the video and not recording the video as the stream is ongoing you can use `MediaSource` attached to a `<video>` element and the elements' `waiting` element to determine when to fetch the next chunks.

**Comment by guest271314** [comment] 2018-04-07 21:03
@benjamingr If the requirement is only displaying the video and not recording the video as the stream is ongoing you can use `MediaSource` attached to a `<video>` element and the elements' `waiting` element to determine when to read or fetch the next chunks of the media stream.

**Comment by domenic** [comment] 2018-04-07 21:03
@guest271314 in the future, please use the edit function, instead of deleting and re-posting new responses. That causes everyone on the thread to get separate emails (three so far).

**Comment by guest271314** [comment] 2018-04-07 21:10
@domenic Got it. Was considering whether or not to link to the issues and efforts have put into, what appears to be, a similar implementation as what have proposed at HTML issues at least twice to date; or, if OP is describing a different requirement than https://github.com/whatwg/html/issues/3593.

**Comment by guest271314** [comment] 2018-04-07 21:55
It is currently possible to store `ImageData` or `ImageBitmap` (video frames) and `AudioBuffer` (audio) objects at the server as raw data, request N chunks of `ImageBitmap` and `AudioBuffer` pairs (as "media segments"; see https://github.com/whatwg/html/pull/2814; also https://github.com/w3c/ServiceWorker/issues/913; https://stackoverflow.com/q/45024915) and stream the presentation by painting the image to `<canvas>` and combining the audio using Web Audio API at a single `MediaStream` set at `srcObject` of a single `<video>` element. This requires creating the media segments which will be requested first, or parsing the file client side to extract the video and audio tracks, then setting those tracks to a `MediaStream` or `MediaSource` https://dev.w3.org/html5/html-sourcing-inband-tracks/.

Have not yet achieved creating a `.webm` file containing both audio and video tracks from the video frame and audio buffer as a distinct media segment at client side only without using `MediaRecorder` first to create a single `.webm` file from one or more of any of the media types which the particular browser can play at `<video>` element first https://github.com/guest271314/MediaFragmentRecorder, though it should also be possible to add audio tracks to the `.webm.` file created at https://github.com/thenickdude/webm-writer-js, where the resulting file can be passed to `appendBuffer()` of `MediaSource` `SourceBuffer` as an `ArrayBuffer`.

**Comment by guest271314** [comment] 2018-04-07 22:01
@domenic One question that do have is why `fetch()` cannot emulate a `<video>` media source provider when making media fragment requests? The URL is stripped of the media fragment URI by fetch algorithm, correct?

**Comment by domenic** [comment] 2018-04-07 22:02
@guest271314 this is all very off-topic for this thread. Please do not hijack threads that other people have opened with your own questions. Instead use something like StackOverflow.

**Comment by guest271314** [comment] 2018-04-07 22:08
@domenic From perspective here not appraise the content of the comments made so far in this thread as off-topic at all. Asking questions is not "hijacking" anything. This entire universe is based on questions and answers. If you decide the input is not in accord with your organizations' policies, will delete the lot of it from your organizations' boards forthwith; or feel free to do the same yourself, in your capacity as an owner, without rancor.

**Comment by domenic** [comment] 2018-04-07 22:10
@guest271314 yes, please delete; it is definitely off-topic. For future reference, is is not appropriate to ask your own questions on other peoples' WHATWG issue threads; those are for interactions between the people posting those threads and the maintainers, and not a place for you to ask your own questions. It is definitely hijacking, and not appreciated.

**Comment by guest271314** [comment] 2018-04-07 22:15
> For future reference, is is not appropriate to ask your own questions on other peoples' WHATWG issue threads; those are for interactions between the people posting those threads and the maintainers, and not a place for you to ask your own questions. It is definitely hijacking, and not appreciated.

Was not aware that the policy was only for maintainers to ask questions. Again, no, not "hijacking" anything. That is an exaggeration. Your policy is clear now.

**Comment by benjamingr** [comment] 2018-04-08 07:11
@ricea 
> @benjamingr You can hack something together using a mixture of Range requests and fetch abort, but it won't be pretty.

Range requests require support from the origin server and it would still mean multiple requests (which I'd rather avoid), exposing the watermarks or having `fetch` respect backpressure would either solve my case - which I believe represents a rather common one and the whole reason we have streams (to read part of the content and not all of it and control how much is read).

**Comment by benjamingr** [comment] 2018-07-25 11:42
I was going to go ahead and close this since it can be implemented on top of ` cache: 'no-store'` as a lower level primitive and letting users handle watermarks which would require a lot of user code but would be doable.

I noticed the crbug @ricea linked to has issues and I'm not sure I understood them:

> I'm very interested in what other implementers feel about this. Maybe we can change "should ignore the suspension request" to "may ignore the suspension request" ?

I might be misunderstanding but wouldn't that take the capability away?

**Comment by benjamingr** [comment] 2018-07-31 09:06
@ricea 

> Actually, the opposite. The intent is to allows browsers to provide the capability even for cacheable responses.

That's awesome, if you would like - we are using streaming fetch in production to a great extent and would be happy to provide feedback like we have done for other specs like WebRTC in the past.

Is there an ETA for when we can test it out and experiment with it?

**Comment by ricea** [comment] 2018-07-31 13:36
@benjamingr Feedback is always welcome, but we ran into performance problems last time we tried to turn it on more broadly: https://bugs.chromium.org/p/chromium/issues/detail?id=824650

I need to do careful analysis to find the cause of the problems, and I won't have time for it in the immediate future.

Sorry I don't have better news for you.

I'm going to close this issue now. If you have further questions, please comment on one of the crbugs.

**Closed by ricea** 2018-07-31 13:36 UTC
Labels: addition/proposal, needs implementer interest, topic: streams

**Comment by benjamingr** [comment] 2018-07-31 14:06
@ricea thanks, pinged you via email and offered feedback - let me know if there is any way I can push this and thanks for clarifying that this is the intended behaviour. 

Now looking forward to it being fixed in Chrome and other browsers turning the option on by default.
