### ISSUE TITLE
Should `new Headers(undefined)` throw?

### ISSUE THREAD

**Issue by wheresrhys** [whatwg/fetch#185] opened 2015-12-17 23:29 UTC
On reading the spec I'm not clear if this is a bug in Chrome or not
```
new Headers(undefined)
VM440:2 Uncaught TypeError: Failed to construct 'Headers': No matching constructor signature.(…)(anonymous function) @ VM440:2InjectedScript._evaluateOn @ VM363:875InjectedScript._evaluateAndWrap @ VM363:808InjectedScript.evaluate @ VM363:664
new Headers()
Headers {}
```

The spec says 

> The Headers(init) constructor, when invoked ... If init is given, fill headers with init. 

Before I raise a Chrome bug could someone clarify if the above behaviour is compliant with the spec. Should passing `undefined` to `Headers()` qualify as 'init is given'?

**Comment by domenic** [comment] 2015-12-17 23:40
Headers(undefined) is the same as Headers(), so yes, it should throw.

**Comment by domenic** [comment] 2015-12-17 23:41
Er, I meant should not. 

This may be fixed in Canary BTW.

**Comment by wheresrhys** [comment] 2015-12-18 08:07
ok, I'll try it out

**Comment by wheresrhys** [comment] 2015-12-18 09:49
No, still broken. Have raised an issue

**Comment by annevk** [comment] 2015-12-18 11:10
You filed a duplicate of https://code.google.com/p/chromium/issues/detail?id=335871. Next time you might want to test in Firefox too, it's usually more correct when it comes to IDL.

**Closed by annevk** 2015-12-18 11:10 UTC
