### ISSUE TITLE
Behavior when consuming a body with for await

### ISSUE THREAD

**Issue by KhafraDev** [whatwg/fetch#1488] opened 2022-09-18 00:36 UTC
In node and deno, due to ReadableStream's async iterator, the following is possible to consume the body more than once without throwing an error:

```js
const response = await fetch('https://example.com')

for await (const chunk of response.body) {}
for await (const chunk of response.body) {}
```

In the second loop, the iterator ends instantly as expected, but this behavior seems strange in regards to the other ways of consuming a body.

Firefox and chromium don't seem to have implemented ReadableStream.asyncIterator for reference, meaning this is only the behavior in environments/engines that have.

**Comment by annevk** [comment] 2022-09-21 07:46
@MattiasBuelens this seems like something you would have an informed opinion about.

**Comment by MattiasBuelens** [comment] 2022-09-21 08:51
This is intended behavior:
* `response.body` always returns the same `ReadableStream`.
* Async-iterating a `ReadableStream` all the way to the end (as with `for await`) leaves it unlocked and in the "closed" state.
* Async-iterating an unlocked closed `ReadableStream` is allowed, although the iteration ends immediately.

I agree that the combination of these behaviors like in your example leads to a bit of a surprising result. But I also don't see a way to fix this... 😕

In hindsight, I would have preferred Fetch to have a `Response.stream()` method instead of a `Response.body` property, similar to [`Blob.stream()`](https://w3c.github.io/FileAPI/#stream-method-algo) (see https://github.com/whatwg/streams/issues/1105#issuecomment-771210640). Then it would be immediately obvious that calling `stream()` twice should throw an "already used" error. But I guess that ship has sailed?

**Comment by annevk** [comment] 2022-09-21 10:11
Yeah, we could possibly change it for requests, but that would be rather awkward.

**Comment by annevk** [comment] 2022-10-24 13:49
Closing this per prior comments.

**Closed by annevk** 2022-10-24 13:49 UTC
Labels: topic: api
