### ISSUE TITLE
Should `status = 0` be considered `ok` for `mode: no-cors`-requests?

### ISSUE THREAD

**Issue by ulken** [whatwg/fetch#1140] opened 2021-01-19 19:37 UTC
According to the [WHATWG Spec.](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque), `status` should be set to `0` for a so called `opaque` response stemming from a `mode: "no-cors"`-request. Interestingly enough, it's not considered an "OK" response in regards to `response.ok` (only includes `2xx`).

I personally find this unexpected and confusing. Therefore, can we make an exception and treat `0` as OK for `mode: no-cors`-requests?

This issue first appeared in [ky](https://github.com/sindresorhus/ky/issues/305) which throws an error if `response.ok = false`.

**Comment by domenic** [comment] 2021-01-19 19:51
This feels likely too late to change, but I will note that a similar thing bit me: see https://github.com/whatwg/whatwg.org/commit/28f6c907085b0a672f63298a6d480abe9e05b0f5#diff-0f2d232da1d117cf8bf862b3ccaad7b646eaee7c43f271fb5dad4ced95fdf8e5L69

**Comment by ulken** [comment] 2021-01-19 19:53
Hum, just read this further down:

> In other words, an opaque filtered response and an opaque-redirect filtered response are nearly indistinguishable from a network error.

> This also means that JavaScript APIs, such as response.ok, will return rather useless results.

So, guess it's expected then?

What's the motivation for such behavior?

**Comment by wanderview** [comment] 2021-01-19 20:55
For security we cannot leak any information about the opaque response; including whether it succeeded or not.  So given its success status is unknown, do you make ok() return true or false?  If it returned true many developers would assume it was a success, when in fact it is unknown.  Therefore it returns false.  While inconvenient, it at least makes it more likely that developers understand the limitations of opaque responses.

At the end of the day, the issue is with opaque responses and not `ok()`.  I would recommend moving to CORS if you can.

**Comment by annevk** [comment] 2021-01-20 07:22
Thanks @wanderview. I hope that reply suffices.

**Closed by annevk** 2021-01-20 07:22 UTC

**Comment by ulken** [comment] 2021-01-20 07:57
Alright, thank you for clarifying.
