### ISSUE TITLE
Consider splitting `document` into `document` and `nested-document`.

### ISSUE THREAD

**Issue by mikewest** [whatwg/fetch#755] opened 2018-06-05 07:33 UTC
As [discussed in the context of `Sec-Metadata`](https://github.com/w3ctag/design-reviews/issues/280#issuecomment-394598257), it might be useful to clearly distinguish between top-level and nested navigation requests by splitting the `document` destination into `document` and `nested-document`.

@annevk notes that this might be a breaking change, as folks might be relying on the existing `document` destination that's exposed on `Request` objects. @wanderview, @jakearchibald: WDYT?

**Comment by wanderview** [comment] 2018-06-05 13:24
Since Request.destination was only relatively recently shipped in browsers, now might be the time to make this change.  Sites would need to adapt, but they could do `evt.request.destination.includes('document')` or something.

FWIW, this better matches what firefox uses internally:

https://searchfox.org/mozilla-central/rev/292d295d6b084b43b70de26a42e68513bb7b36a3/dom/base/nsIContentPolicy.idl#87-96

Which we then map to the exposed `document` destination:

https://searchfox.org/mozilla-central/rev/292d295d6b084b43b70de26a42e68513bb7b36a3/dom/fetch/InternalRequest.cpp#274-277

I was wondering if this change would interact badly with the [portals proposal][], but I guess the navigation request would have to complete well before any portal is promoted from 3rd party to 1st party.

[portals proposal]: https://github.com/KenjiBaheux/portals/blob/master/explainer.md

**Comment by mikewest** [comment] 2018-06-05 13:45
Thanks, @wanderview, that's helpful. Who should we loop in from WebKit/Edge to see if they'd be willing to do the same?

**Comment by wanderview** [comment] 2018-06-05 13:56
I think @youennf can speak to the fetch API in webkit.

I'm not sure for edge.  Maybe @aliams or @jungkees can help.

**Comment by youennf** [comment] 2018-06-05 15:12
I am not totally clear about the intent of this change.
Is it to allow a simpler definition/implementation of Sec-Metadata?
Is it to allow service worker to start acting as some sort of security proxy that could decide to stop loads based on a better knowledge of the client triggering the fetch?

FWIW, WebKit has this is-top-level-navigation concept, although at a slightly lower level. The proposed change seems ok from that prospective.
The same information could be made available elsewhere in a backward compatible way: fetch event or service worker client for instance.

**Comment by youennf** [comment] 2018-06-05 17:57
That seems reasonable to me.

Given a service worker might expose the same data that servers would provide directly, it makes sense to me that a service worker should get the same level of information as the one provided to the server through Sec-Metadata, at least for navigation loads.
The cause member information does not seem to be exposed to service worker.
The same-site value might be somehow exposed although computing the public suffix might be more easily done by the browser.

**Comment by annevk** [comment] 2018-06-06 04:50
@youennf same-site doesn't need to be exposed as we know service workers are always same-origin.

**Comment by jakearchibald** [comment] 2018-06-06 05:12
Isn't this information (and more) already available by getting the client associated with [`fetchEvent.targetClientId`](https://w3c.github.io/ServiceWorker/#fetch-event-targetclientid), then looking at its [`client.ancestorOrigins`](https://w3c.github.io/ServiceWorker/#client-ancestororigins)?

**Comment by wanderview** [comment] 2018-06-06 13:18
Do you mean `resultingClientId`?  You won't be able to look at any information about that client until after the fetch completes, right?

Also, I don't think `client.ancestorOrigins` has been implemented widely yet due to privacy concerns being resolved with the main thread ancestorOrigins API.  I think we still have `client.frameType`, though, until that is resolved.

**Comment by jungkees** [comment] 2018-06-11 18:18
The idea of exposing the header to service workers sounds interesting.

My initial thought is what'd be a downside of maintaining the target member? The values of the destination look more like what the request's resulting resource kind would be. If we split them, there seems to be quite a few places that need some clarification. E.g. "A navigation request is a request whose destination is "document" **or "nested-document"**, etc.

> Do you mean resultingClientId? You won't be able to look at any information about that client until after the fetch completes, right?

Yes.

**Comment by jakearchibald** [comment] 2018-06-14 11:41
@wanderview wouldn't `targetClientId` be the right thing to look at here?

**Comment by mikewest** [comment] 2018-06-14 11:46
There seems to be some level of agreement that splitting `document` might be a reasonable thing to do. If I send out a PR against [Fetch](https://fetch.spec.whatwg.org/#concept-request-destination), [HTML](https://html.spec.whatwg.org/#process-a-navigate-fetch), and added some tests, would other vendors implement the change? :)

**Comment by wanderview** [comment] 2018-06-15 15:03
> @wanderview wouldn't targetClientId be the right thing to look at here?

I think we answered this on IRC.  Since targetClientId will be null for cross-origin targets or new top level windows it can't really be used reliably to determine the type of request.

**Comment by mikewest** [comment] 2018-10-24 10:01
@arturjanc reminded me that I never came back to this.

Do y'all think it's worth trying to poke at `destination` in this way? Or would y'all prefer introducing a new concept on `request` objects instead?

**Comment by annevk** [comment] 2018-10-26 07:43
I'd prefer changing `destination` over adding a new concept.

**Comment by mikewest** [comment] 2018-10-26 14:08
I put up https://github.com/whatwg/fetch/pull/819. I'll find time to put up an HTML counterpart.

**Comment by mikewest** [comment] 2019-03-14 09:19
In https://github.com/mikewest/sec-metadata/issues/16, @annevk suggested that we move this to the request's `mode` instead, which seems fine.

**Comment by yoavweiss** [comment] 2019-03-14 09:26
When discussing the [definition of  Prefetch's processing model](https://github.com/whatwg/html/pull/4115) it was raised that we probably want to limit it in some cases to top-level navigations. In that context, a `request.destination` that indicates a top-level navigation would be helpful to us, and would cleanly map to the `as` attribute already exposed on `HTMLLinkElement`.

/cc @kinu @jkarlin

**Comment by mikewest** [comment] 2019-03-14 09:29
Would a `request.mode` of `navigate` vs `nested-navigate` work for you as well, @yoavweiss? That's what @annevk suggested in the linked bug.

**Comment by yoavweiss** [comment] 2019-03-14 09:41
It will require us to rewire some `as` values to request mode, or to come up with some other opt-in that maps into request mode directly, which is feasibale, but not as clean. Admittedly, I haven't yet read https://github.com/mikewest/sec-metadata/issues/16 regarding the reasoning for `request.mode`. I'll do that now! :)

**Comment by mikewest** [comment] 2019-03-14 09:56
I don't have strong opinions either way. As long as I can distinguish nested vs. non-nested navigations in some way, I'm happy. We could even do both. Whatever. :)

**Comment by yoavweiss** [comment] 2019-03-14 09:59
OK, I read the thread on the issue, and IIUC there's still an open question there on whether we want to expose `request.destination` to servers, right?

If it is exposed, I think it'd be cleaner to have nestedness be part of `destination`.

**Comment by yoavweiss** [comment] 2019-03-14 10:15
If it ends up not being exposed, and "nested-navigate" `request.mode` is a thing, I guess we can somehow live with that spec-complexity and map `as` values to that.

**Comment by annevk** [comment] 2021-01-29 18:02
This was fixed by #948.

**Closed by annevk** 2021-01-29 18:02 UTC
Labels: addition/proposal, topic: api
