### ISSUE TITLE
Link preload's `as` value should impact Accept headers

### ISSUE THREAD

**Issue by yoavweiss** [whatwg/fetch#580] opened 2017-08-18 12:28 UTC
As commented on https://github.com/w3c/preload/issues/95#issuecomment-305237486 Fetch should indicate that `as` also impacts the request type, and therefore impacts the `Accept` headers that preload requests go out with.

**Comment by yoavweiss** [comment] 2017-08-18 12:32
Is there a normative way to map from a request's `destination` to a `type`?

**Comment by annevk** [comment] 2017-08-21 08:21
Closing this as a duplicate of #581.

**Closed by annevk** 2017-08-21 08:21 UTC
