### ISSUE TITLE
Proposal: add a boolean property `notModified` to `Response`

### ISSUE THREAD

**Issue by taoso** [whatwg/fetch#1440] opened 2022-05-15 05:02 UTC
The currently `Response` has a `redirected` property to indicate redirections during the fetch call.

However, there is no way to check whether the server respond a `304 Not Modified` response. But why we need to check this status?

I am developing [WebFeed](https://github.com/taoso/webfeed), a lightweight web feed reader extension. In order to remind users there are new files published, WebFeed needs to check the subscribed feeds (RSS or Atom) periodically, by the fetch API. 

For most blog or website, it is seldomly to publish content very frequently. Daily or weekly is good, and monthly or even yearly is not rare. So if the server support conditional request, the most fetch request sent by WebFeed will receive a `304 Not Modified` response, which means there is nothing new.

Parse these XML feeds without small memory consumption is not a trival task. So I wish to avoid useless parsing procedure as mush as possible. If the server respond a 304 status, it indicates there is no change during last fetch. There is nothing to parse. So if the `Response` has a `notModified` property, WebFeed could notice that and do not parse the response body again.

I am not a browser engineer. But given the support of the `redirected` property, I do not think implementing this proposal is a hard task.

Please make your comments of this proposal. Thanks.

**Comment by annevk** [comment] 2022-05-16 07:22
This is a duplicate of #40. Note that if you keep the ETag information around you can make your own conditional requests and then you will actually get a 304 and not a 200 back.

**Closed by annevk** 2022-05-16 07:22 UTC
Labels: addition/proposal

**Comment by taoso** [comment] 2022-05-16 08:04
@annevk Sorry for duplication.

> Note that if you keep the ETag information around you can make your own conditional requests and then you will actually get a 304 and not a 200 back.

Thanks for your kindly advice. A fetch with conditional request header will get a 304 status code. However, it is not wise to save the ETag or last modified time manually by developer, as the browser has stored them. So it do really make sense to exposed by the Response object.

**Comment by annevk** [comment] 2022-05-16 14:57
Depending on your goals, it can be wise, as it'll save the browser from doing redundant processing (getting the full response from the cache and returning that).
