### ISSUE TITLE
um... blasphemy but... what about .xml() ?

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/fetch#151] opened 2015-11-02 08:13 UTC
I know, I know stop throwing tomatoes at me... but stupid piece of crap JSON's lack of comment support means we are doing things like this for localization (adding a global JS object! yeah... OMFG bad!!):

https://github.com/mozilla/remote-newtab/blob/gh-pages/src/locale/newTab.js

The above is better suited for XML, as we can have comments there. I imagine there is probably still quite a bit of XML out there also and I doubt browsers are going to drop support for it any time soon, yada yada yada....

**Comment by jakearchibald** [comment] 2015-11-02 08:34
Dupe of https://github.com/whatwg/fetch/issues/16

A method that took a stream…

```js
fetch(url).then(r => parseDoc(r.body)).then(doc => …)
```

…or a transform stream would be a better solution here.

**Closed by jakearchibald** 2015-11-02 08:34 UTC

**Comment by marcoscaceres** [comment] 2015-11-02 08:44
... yeah... I guess, but it seems to be putting purity before developer need. I'm happy to wait and see what feedback comes back from the wider web once fetch gets more adoption.

**Comment by annevk** [comment] 2015-11-02 09:41
Well, please also consider the affect on potential non-browser implementations if we suddenly import all of XML/HTML as a dependency.

It's not really purity I think, just basic software engineering practices.

**Comment by marcoscaceres** [comment] 2015-11-02 11:07
Ok, I was not aware we were now in the business of specifying behaviour for non-browser implementations. That's a bit of a worry, specially given the dependencies on same origin and other browser-environment specific quirks. Which other platforms are implementing fetch?

**Comment by annevk** [comment] 2015-11-02 11:39
I believe there's a number of implementations available for Node.js. They might leave out the CORS aspect there though since it makes less sense.

**Comment by yanlee26** [comment] 2017-07-05 07:08
I do not think this is a good solution

**Comment by marcoscaceres** [comment] 2017-07-05 07:12
@yanlee26, with streams being part of to fetch, you can make a really nice SAX parser for XML. Also using @jakearchibald's solution works well.

**Comment by jakearchibald** [comment] 2017-07-05 07:36
@yanlee26 you need to be clear on what in particular you don't like, along with reasons why, otherwise your comment is of no value.
