### ISSUE TITLE
Should `body` be set up as a byte stream?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/fetch#1572] opened 2022-12-14 02:37 UTC
Currently this succeeds on Firefox and fails on Chrome:

```js
new Response(new Uint8Array([1,2])).body.getReader({mode: 'byob'})
```

Firefox creates body as a byte stream: https://searchfox.org/mozilla-central/rev/43cb6eca1c3069d46d589d52ab4949257e630d19/dom/streams/ReadableStream.cpp#871

But the spec does not actually use "[set up with byte reading support](https://streams.spec.whatwg.org/#readablestream-set-up-with-byte-reading-support)" algorithm, and I see no relevant test for this.

I think it should support byte stream as fetch is all about bytes. What do you think?

**Comment by domenic** [comment] 2022-12-14 02:39
Dupe of #267.

**Closed as completed by domenic** 2022-12-14 02:39 UTC
