### ISSUE TITLE
should navigation requests really be same-origin or no-cors?

### ISSUE THREAD

**Issue by wanderview** [whatwg/fetch#101] opened 2015-08-04 19:28 UTC
Step 2.2 of [HTTP Fetch][] currently has the following note:

> The underlying assumption here is that all client requests use mode "same-origin", which is currently not explicitly stated for navigation requests. 

This is necessary for the step 2.2 checks to properly block opaque responses from being used to intercept a navigation.

It seems, however, forcing navigations to same-origin has other consequences.  Mainly, it would seem to prevent navigations from following cross origin redirects as they currently do on the web:

* When a 30x is encountered step 5 of [HTTP Fetch][] recursively calls [Main Fetch][] using the new location.
* Step 8 of [Main Fetch][] checks to see if the current URL is same origin, and if its not it explicitly returns NetworkError for same-origin RequestMode.

I ran into this while trying to make our navigations same-origin.  We have a test that does `respondWith(fetch(evt.request))` for a navigation request to a cross-origin 308.  This fails when RequestMode is same-origin due the issue above.  When navigations are RequestMode no-cors, then this works.

Note, currently both chrome and firefox implement navigations as no-cors and block opaque interception using a secondary check.

[HTTP Fetch]: https://fetch.spec.whatwg.org/#http-fetch
[Main Fetch]: https://fetch.spec.whatwg.org/#main-fetch

**Comment by jakearchibald** [comment] 2015-08-05 10:04
Isn't this fixed with https://github.com/whatwg/fetch/issues/66?

When doing `respondWith(fetch(evt.request))`, where `evt.request` is a navigation, the request has a manual redirect flag. The redirect is sent back to `respondWith`, and the right thing happens.

**Comment by wanderview** [comment] 2015-08-05 14:35
I don't see anything in the spec which says navigations should have the manual redirect flag.  I guess this is another spec integration thing.  Would be nice to at least have a note in the meantime.

**Comment by horo-t** [comment] 2015-08-06 05:19
I didn't know that the redirect flag of navigation request is "manual".
I think this will change the behavior of existing Service Workers.

Example:
- The server returns 302 redirect responses for these URLs:
  1. https://www.example.com/scope/in_scope_redirect -> https://www.example.com/scope/dir/destination
  2. https://www.example.com/scope/out_scope_redirect -> https://www.example.com/out_scope/destination

- The server returns 200 responses with the body "\<img src='./image.png'\>" for these URLs:
  1. https://www.example.com/scope/dir/destination
  2. https://www.example.com/out_scope/destination

- A serviceworker.js is registered for https://www.example.com/scope/
```javascript
  self.addEventListener('fetch', function(event) {
      if (event.request.url == 'https://www.example.com/scope/in_scope_sw_redirect') {
        event.respondWith(fetch('https://www.example.com/scope/dir/destination'));
      } else if (event.request.url == 'https://www.example.com/scope/out_scope_sw_redirect') {
        event.respondWith(fetch('https://www.example.com/out_scope/destination'));
      } else {
        event.respondWith(fetch(event.request));
      }
    });
```

- The current behavior in Chrome:
 1. When the user opens "https://www.example.com/scope/in_scope_redirect".
    The URL bar of the pege is "https://www.example.com/scope/in_scope_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.

 2. When the user opens "https://www.example.com/scope/out_scope_redirect".
    The URL bar of the pege is "https://www.example.com/scope/out_scope_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.

 3. When the user opens "https://www.example.com/scope/in_scope_sw_redirect".
    The URL bar of the pege is "https://www.example.com/scope/in_scope_sw_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.

 4. When the user opens "https://www.example.com/scope/out_scope_sw_redirect".
    The URL bar of the pege is "https://www.example.com/scope/out_scope_sw_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.


- If the navigation requests of redirect flag is "manual".
 1. When the user opens "https://www.example.com/scope/in_scope_redirect".
    fetch(event.request) returns a "opaqueredirect" response which points to "https://www.example.com/scope/dir/destination".
    The URL bar of the pege is changed to "https://www.example.com/scope/dir/destination".
    The page sends a navigation request "https://www.example.com/scope/dir/destination" via the Service Worker.
    The page sends a fetch request "https://www.example.com/scope/dir/image.png" via the Service Worker.

 2. When the user opens "https://www.example.com/scope/out_scope_redirect".
    fetch(event.request) returns a "opaqueredirect" response which points to "https://www.example.com/out_scope/destination".
    The URL bar of the pege is changed to "https://www.example.com/out_scope/destination".
    The page will not be controlled by the Service Worker.
    The page sends a navigation request "https://www.example.com/out_scope/destination" which is not handled by the Service Worker.
    The page sends a fetch request "https://www.example.com/out_scope/image.png" which is not handled by the Service Worker.

 3. When the user opens "https://www.example.com/scope/in_scope_sw_redirect".
    The URL bar of the pege is "https://www.example.com/scope/in_scope_sw_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.

 4. When the user opens "https://www.example.com/scope/out_scope_sw_redirect".
    The URL bar of the pege is "https://www.example.com/scope/out_scope_sw_redirect".
    The page sends a fetch request "https://www.example.com/scope/image.png" via the Service Worker.

**Comment by horo-t** [comment] 2015-08-06 05:22
Umm...
I didn't noticed this change. https://github.com/whatwg/fetch/commit/44c2846340247a53af1b55b38f183fe76aba3fc7
This change removed "10. If response's final url flag is unset, set response's url to request's url." from "4 Fetching" section.

After this change, iii. and iv. should be 
 iii. When the user opens "https://www.example.com/scope/in_scope_sw_redirect".
    The URL bar of the pege is changed to "https://www.example.com/scope/dir/destination".
    The page sends a fetch request "https://www.example.com/scope/dir/image.png" via the Service Worker.

 iv. When the user opens "https://www.example.com/scope/out_scope_sw_redirect".
    The URL bar of the pege is changed to "https://www.example.com/out_scope/destination".
    The page will not be controlled by the Service Worker. (right??)
    The page sends a fetch request "https://www.example.com/out_scope/image.png" which is not handled by the Service Worker. (right??)

Is this an intended behavior change?
Or is my understanding incorrect?

**Comment by annevk** [comment] 2015-08-06 06:37
@horo-t no, that change got reverted. See "main fetch", step 15.

**Comment by annevk** [comment] 2015-08-06 06:45
And changing the behavior of existing service workers was the point behind #66.

HTML also already states that navigation happens with the "manual redirect flag" set, which is the old way of saying 'redirect mode set to "`manual`"'. I'll leave this open, but given that I expect HTML patching to begin within a manner of weeks, I don't really see the point of adding a note now. Please let me know if you disagree and I'll add the note nonetheless.

**Comment by horo-t** [comment] 2015-08-06 13:29
@annevk
Ah, I understand now. Thank you.

**Comment by annevk** [comment] 2015-08-11 08:23
Marking this as duplicate of #106. If we decide there navigation needs to be done differently, we can change Fetch.

**Closed by annevk** 2015-08-11 08:23 UTC
