### ISSUE TITLE
Document which request fields are required

### ISSUE THREAD

**Issue by jyasskin** [whatwg/fetch#949] opened 2019-10-08 23:18 UTC
It's not clear from https://fetch.spec.whatwg.org/#concept-request which fields another specification needs to set in order to [fetch](https://fetch.spec.whatwg.org/#concept-fetch) the request. I believe https://www.w3.org/TR/appmanifest/#obtaining forgets to set the client as a result.

I think the required fields are:

* [client](https://fetch.spec.whatwg.org/#concept-request-client) (because [fetch](https://fetch.spec.whatwg.org/#concept-fetch) uses "request’s client’s global object" without checking whether the client is null)
* [URL](https://fetch.spec.whatwg.org/#concept-request-url)

**Comment by annevk** [comment] 2019-10-09 14:07
Hmm, client should maybe be optional, though App Manifest ought to set it. I'd also expect mode/destination to typically be set, even though they have defaults at the moment.

This is a duplicate of #186 of sorts.

**Comment by jyasskin** [comment] 2019-10-11 17:12
Yep, and the "write a create-a-request algorithm" suggestion in https://github.com/whatwg/fetch/issues/907#issuecomment-495299306 (where you also thought client should _not_ be optional :wink:). FWIW, I think it will be easier to obey the "how to use fetch from other specs" advice if it's in a separate section than if it's mixed into the definitions of the fields.

**Comment by annevk** [comment] 2021-03-11 12:36
Let's fold this into #1143.

**Closed by annevk** 2021-03-11 12:36 UTC
Labels: clarification
