### ISSUE TITLE
Question - Why can't the request be cloned?

### ISSUE THREAD

**Issue by cowwoc** [whatwg/fetch#939] opened 2019-09-22 04:51 UTC
Given:

```
const request = new Request(someUri,
{
	method: "POST",
	headers: someHeaders,
	body: JSON.stringify({
		name: "name",
                parent: null
	})
});

const copyOfRequest = request.clone();
console.log("original: " + await request.text());
console.log("copy: " + await copyOfRequest.text());
```

The second log statement fails with `TypeError: Failed to execute 'text' on 'Request': body stream is locked` on `Chrome Version 77.0.3865.90 (Official Build) (64-bit)`.

Is this behavior by design?

**Comment by cowwoc** [comment] 2019-09-22 05:27
I just discovered that swapping the order of the log statements fixes the problem. Meaning, if one consumes the body of the clone first, then consumes the original then all is well. But if one consumes the original, then consumes the clone, then it fails.

Is this by design?

**Comment by annevk** [comment] 2019-09-23 08:41
That sounds like an implementation bug.

**Comment by cowwoc** [comment] 2019-09-23 13:49
Filed a bug report at https://bugs.chromium.org/p/chromium/issues/detail?id=1006780

**Comment by annevk** [comment] 2019-09-23 13:59
Thanks, I guess the one remaining question here is whether this is covered by web-platform-tests already.

**Comment by cowwoc** [comment] 2019-09-23 14:32
@annevk I assume you will check and get back to us here? This would certainly help get vendors aligned on this point :)

**Comment by annevk** [comment] 2019-09-23 14:38
At some point unless someone beats me to it.

**Comment by annevk** [comment] 2021-01-30 14:13
Since nobody ended up being able to reproduce this I'm going to close this.

**Closed by annevk** 2021-01-30 14:13 UTC
Labels: topic: streams
