### ISSUE TITLE
Setting body as ReadableStream at POST request

### ISSUE THREAD

**Issue by guest271314** [whatwg/fetch#439] opened 2016-12-18 18:49 UTC
MDN documentation of [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) states:

> Note: The body type only can be a Blob, BufferSource, FormData, URLSearchParams, USVString or ReadableStream type, so for adding a JSON object to the payload it need to be stringify that object.

Though at MDN documentation for [`Request()`](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) `ReadableStream` is not listed as valid option.

> body: Any body that you want to add to your request: this can be a Blob, BufferSource, FormData, URLSearchParams, or USVString object. Note that a request using the GET or HEAD method cannot have a body.

Could not find an example of the same at the specification. After searching before posting the question here or at stackoverflow, found that the question had already recently been asked [Fetch with ReadableStream](http://stackoverflow.com/questions/40939857/fetch-with-readablestream).

Tried a slightly different pattern than the `javascript` at Question at SO, though result was essentially the same. Is this possible? Is MDN documentation incorrect? If possible, what is the correct pattern to achieve the expected result of `fetch()` reading from `ReadableStream` to populate the `body` of a `POST` request?

Edit: Related https://github.com/whatwg/fetch/issues/378

**Comment by annevk** [comment] 2016-12-19 08:41
This is a duplicate of #88 that is being fixed by #425. This is new functionality that's not yet ready, but will be soon.

**Closed by annevk** 2016-12-19 08:41 UTC
