### ISSUE TITLE
Preflight for Content-Type request header

### ISSUE THREAD

**Issue by antosart** [whatwg/fetch#1269] opened 2021-07-20 07:30 UTC
If I understand correctly, according to the spec `Content-Type: text/plain;charset=utf8,text/html` is [cors-safelisted](https://fetch.spec.whatwg.org/#cors-safelisted-request-header) while `Content-Type: text/plain,text/html` is not.

This happens because [parsing](https://mimesniff.spec.whatwg.org/#parse-a-mime-type) `Content-Type: text/plain;charset=utf-8,text/html` returns as mimetype `text/plain` and as parameter `(charset, utf8,text/html)` while [parsing](https://mimesniff.spec.whatwg.org/#parse-a-mime-type) `Content-Type: text/plain,text/html` returns as mimetype 
 type `text` with subtype `plain,text/html`.

I believe both headers above should issue preflight requests (in fact, they do in Firefox).

**Comment by antosart** [comment] 2021-07-20 07:30
cc @yutakahirano @MattMenke2

**Comment by annevk** [comment] 2021-07-20 10:36
This seems like a duplicate of #838. It's somewhat surprising Firefox is not compliant here. I wonder how that came about.

**Closed** 2021-07-20 10:55 UTC
