### ISSUE TITLE
Body should not be transmitted if service worker intercepts request

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/fetch#572] opened 2017-08-01 13:16 UTC
https://fetch.spec.whatwg.org/#http-fetch 3.3.1 "Transmit body for request".

If the service worker has provided a response, it should have transmitted the body itself in a separate call to fetch, or transmitting is unnecessary since the SW provided a response from the cache API or similar.

**Comment by annevk** [comment] 2017-08-02 11:44
cc @yutakahirano 

So this relates to upload streams. Main question I guess is whether a stream gets drained if the service worker doesn't touch it? (If no, this means that a page can observe a service worker in a new way, maybe unexpected.)

**Comment by annevk** [comment] 2017-08-02 11:44
cc @domenic

**Comment by wanderview** [comment] 2017-08-02 13:51
Do we care about sites observing there is a service worker?  We break that in other places.

For example, this code:

```
let response = await fetch(crossOriginURL, { mode: 'no-cors' });
let text = await response.text();
```

Without a service worker the response will always be opaque and the text will be empty string.  A service worker can return a basic Response, though, and the spec currently says to expose that basic response to the outer page.  So in that case the body could be observed.   (There was a spec issue about this case, but I don't have it handy at the moment.)

**Comment by jakearchibald** [comment] 2017-08-02 13:55
Seems fine that it's observable. Ideally it would cancel the body stream if it doesn't need it.

**Comment by annevk** [comment] 2017-08-02 14:03
Yeah, I wonder how it works for responses created in a service worker today. Since that also somewhat depends on how we cross the boundaries between Document<>Fetch<>Service Worker<>Network.

**Comment by domenic** [comment] 2017-08-04 22:42
I'm having a bit of trouble understanding that step (3.3.1) in the first place, but I think it is probably unnecessary, yeah... I mean, the body needs to get from the main thread to the service worker, but it sounds like that step is not how it happens? How does it happen?

**Comment by wanderview** [comment] 2017-08-04 23:20
It effectively needs the transfer thing we've talked about for postMessage.

**Comment by annevk** [comment] 2017-08-07 07:58
Before streams the way it happened is that requests and responses (as concepts) can just be transferred across threads. But JavaScript streams were never backed by internal streams so at that point that strategy started falling apart and we haven't really made an effort to patch it back together again.

**Comment by yutakahirano** [comment] 2017-08-09 05:58
Sorry for the delay. Probably I added the sentence but it doesn't make sense at all. I'll create a PR which removes the item.

**Comment by annevk** [comment] 2017-08-09 07:04
Note that just removing it doesn't really work either, since it results in XMLHttpRequest not getting the tasks queued that it needs for uploads. Unless I'm missing something.

**Comment by annevk** [comment] 2021-02-15 17:31
So if we remove this line, XMLHttpRequest wouldn't see uploads if there was a service worker. Has anyone tested this?

**Comment by yutakahirano** [comment] 2021-02-16 12:45
I haven't checked this but I don't think service worker provides fake upload progress in our implementation. @mfalken, do you know?

**Comment by yutakahirano** [comment] 2021-02-17 01:44
Confirmed. No upload progress events are delivered on Chromium.

**Comment by yutakahirano** [comment] 2021-02-17 05:31
#1144 is fixing this.

**Closed** 2021-02-18 13:40 UTC
Labels: needs tests, topic: streams
