### ISSUE TITLE
Do we have any information about fetching in case of an error?

### ISSUE THREAD

**Issue by Mtnt** [whatwg/fetch#531] opened 2017-04-25 09:12 UTC
For example a timeout: In case of timeout we have no way to figure out what exactly happened - we just get a `TypeError('Network request failed')`. It`s not very convenient...

**Comment by annevk** [comment] 2017-04-25 09:13
Duplicate of #526 as far as I can tell.

**Closed by annevk** 2017-04-25 09:13 UTC
