### ISSUE TITLE
Why is media fragment uri stripped from fetch URL?

### ISSUE THREAD

**Issue by guest271314** [whatwg/fetch#557] opened 2017-06-21 00:50 UTC
```
fetch("https://upload.wikimedia.org/wikipedia/commons/b/be/Hidden_Tribe_-_Didgeridoo_1_Live.ogg#t=30,50")
```

strips media fragment `#t=30,50` from request at `Network` tab at `DevTools` at chromium. Why?

**Comment by annevk** [comment] 2017-06-28 22:57
https://bugs.chromium.org/p/chromium/issues/detail?id=624278

(Duplicate of #214.)

**Closed by annevk** 2017-06-28 22:57 UTC

**Comment by guest271314** [comment] 2017-06-28 23:52
@annevk [Media Fragment URI](https://www.w3.org/TR/media-frags/) is different from `location.hash`, no? Not sure how links address or resolve issue?

**Comment by guest271314** [comment] 2017-06-29 01:35
@annevk Installed chromium 59. `fetch()` does not include media fragment uri at URL.
